// ============================================================
// AGE OF TOYS — the Storybook Codex.
// Deep lore for every toy, building, tribe and battlefield.
// Loaded lazily by the codex screen only; never ships with the sim.
// ============================================================

export const LORE = {
  factions: {
    classic: 'Before the bricks, before the batteries, there were the Army Men — poured molten into their molds in a factory that no longer exists, boots first, hearts second. They are the oldest law the room has: hold the line, count your soldiers twice, and never let the Kid see you out of formation.\n\nThey do not win by being stronger. They win by being there — every battle, every bedtime, every year the other toys arrived in brighter boxes and louder colors. Ask General Greenboots what the secret is and he will tell you what he tells every recruit fresh off the sprue: "Discipline is just love, standing at attention."',
    bricks: 'The Snap-Bricks arrived in a thousand pieces and considered this a head start. They are the room\'s masons, engineers, and unlicensed architects — a tribe whose answer to every question, from war to weather to hurt feelings, is a wall with a tower on it.\n\nTheir great religion is the Stud and the Tube: everything connects, everything can be rebuilt, and nothing broken is ever truly gone — it is simply a kit for the next attempt. This is why they do not fear the room\'s wars. You cannot frighten a people whose whole body is spare parts.',
    plush: 'The Plushie Horde measures its history not in battles but in hugs survived — each flattened ear and re-stitched seam a campaign ribbon. They are soft the way rivers are soft: gently, patiently, and with the quiet certainty of eventually winning.\n\nIt is a mistake every new toy makes once: assuming the stuffing means surrender. The Horde absorbed the room\'s worst sieges belly-first and waddled out the other side, carrying their wounded, humming lullabies as war songs. Colonel Snug\'s standing order has never changed — "Hold the line. Hug the prisoners."',
    racers: 'The RC Racers were born the morning after a birthday, screaming out of gift wrap at full throttle, and they have broadly declined to slow down since. Their culture is the racing line: the shortest path between any two points in the room, including through your camp.\n\nThey are not reckless — recklessness implies not knowing better. The Racers know exactly better and choose speed anyway, because in their philosophy the finish line forgives everything. Chief Nitro keeps the tribe\'s only sacred relic in the Pit Stop: a battery, still in its packaging, labeled IN CASE OF TOMORROW.',
    bots: 'The Tin Bots are the room\'s newest tribe and its oldest souls — wind-up hearts stamped from sheet metal in a country the atlas no longer lists. Each one runs on a mainspring, a schedule, and a private, carefully-oiled hope that somebody will notice how hard they are trying.\n\nThey march in step because step is all a gear knows, and they fight with the terrible arithmetic of clockwork: every tick spent is a tick closer to winding down. That they spend those ticks defending a room that once left them in a backpack tells you everything about what the manual never printed. Captain Cogsworth was left behind on purpose. He stays on purpose, too.',
  },

  units: {
    worker: 'Every empire in the room stands on the shoulders of a toy no taller than a juice box. Worker Buddies gather, build, repair and rebuild without complaint, and the storybooks are firm on this point: no Worker Buddy has ever lost a war. They have only ever been let down by their generals.',
    scout: 'The scout was built with one oversized virtue — curiosity — and no armor to slow it down. It has seen more of the room than any king and reports all of it faithfully, including the parts nobody believes until it is far too late.',
    soldier: 'The standard-issue soldier of the standard-issue war: one piece, one pose, one purpose. What the mold left out — fear, mostly — nobody has missed.',
    spear: 'Somebody glued a toothpick to a brave toy and invented the pike wall. Cavalry of every tribe learned the lesson the hard way, which is the only way cavalry learns.',
    archer: 'Fires rubber-tipped optimism at high velocity. Archers hold the high shelf of every battle plan — far from the biting, close to the glory.',
    flinger: 'A spoon, a rubber band, and an attitude. The Flinger lobs whatever fits in the cup — marbles, dice, opinions — and gravity does the negotiating.',
    raider: 'A wind-up car with the conscience removed. It exists to arrive uninvited, leave expensively, and be somewhere else by the time the garrison musters.',
    catapult: 'The room\'s heaviest argument. Slow to arrive, slower to leave, and absolutely conclusive about walls.',
    ram: 'A battering ram built from a rolling pin and commitment. Doors, gates and load-bearing pride all answer to it eventually.',
    hero: 'Every toybox produces one: the toy the Kid reached for first, every time. Heroes carry that certainty into battle like a lamp, and other toys fight braver just standing in the light of it.',
    medic: 'Armed with a needle, thread, and unlimited patience. The Medic has heard every battlefield last word and stitched most of them back in mid-sentence.',
    cart: 'The Delivery Cart runs the room\'s oldest trade route — from plenty to shortage and back — and has been robbed so many times it now waves at the raiders by name.',
    hypno: 'The Hypno-Top spins a question into enemy hearts: "Whose side were you on, again?" Few toys can watch it wobble and remember the answer.',
    king: 'The King is not the strongest toy, nor the fastest. The King is the toy the others agreed to believe in — and belief, in this room, is armor thicker than tin.',
    bear: 'The Big Bear Hug is the Plushie Horde\'s heavy infantry and entire foreign policy. It advances at a waddle, absorbs everything the enemy has, and then administers the hug. Survivors describe it as "educational."',
    golem: 'The Brick Golem is what happens when the Snap-Bricks stop building walls and start building a person out of one. Losing pieces doesn\'t stop it; losing pieces is simply how it shares.',
    dragster: 'The Nitro Dragster holds the room record for the hall straightaway and refuses to confirm the rumors about the stairs. Its battle doctrine is one word long: "through."',
    bazooka: 'The Bazooka Man was molded kneeling, which the other army men mistook for humility until the first shot. He has been politely asked to aim away from the goldfish.',
    grenadier: 'Lobs jacks-and-marble grenades with the easy confidence of a toy who read the safety warnings and considered them suggestions.',
    lancer: 'The Pogo Lancer solved the siege problem vertically. Walls, the Snap-Bricks reasoned, only work on toys that stay on the ground.',
    sockpuppet: 'Nobody knits a Sock Puppet — they volunteer, one drawer at a time. In battle they sway unpredictably, which the enemy calls unfair and the Horde calls dancing.',
    drone: 'The Whirly Drone is the Racers\' answer to traffic: fly over it. It hums one note, holds one grudge, and delivers both at altitude.',
    zapbot: 'The Zap Bot carries a static charge it built up crossing the carpet and has been looking for someone to share it with ever since.',
    titanbot: 'The Titan Bot was assembled from the parts of three lesser robots and the ambitions of all three. It walks like a filing cabinet and hits like a dropped one.',
    tank: 'The General\'s Tank is Classic doctrine made metal: arrive slowly, argue conclusively. Its turret has one setting and its treads have flattened every rumor of retreat.',
    colossus: 'The Brick Colossus is the Snap-Bricks\' cathedral that walks. Whole houses of bricks volunteered for the build, and you can still hear them click with pride when it swings.',
    mamabear: 'Mama Bear is what the Horde keeps behind glass marked BREAK IN CASE OF BULLIES. The hug is no longer educational. The hug is final.',
    monster: 'The Monster Truck idles at a volume the room classifies as weather. The Racers built it to answer one question: what if the racing line went through the fort?',
    mecha: 'The Mecha-Titan is the Tin Bots\' masterwork — every spare gear, every saved screw, every quiet evening of maintenance, marching in one chassis. When it winds up, the floorboards apologize in advance.',
    tugboat: 'The Tugboat Gunner ran the bath\'s only ferry line until the wars came; it kept the hull, added the gun, and never quite stopped announcing departures.',
    duckboat: 'The Rubber Duck Raider is proof that morale is a weapon system. It squeaks on the attack. The squeak has never once been described as adorable by anyone it was aimed at.',
    skimmer: 'The Bath Skimmer worked the tub long before the navies came — netting soap, herding ducklings, keeping the water tidy. The wars simply gave its route an escort problem.',
    'navy-classic': 'The Toy Destroyer is the lawful gray backbone of the bath: molded in one piece, briefed in one sentence, unsinkable in one respect — it has never once questioned an order.',
    'navy-bricks': 'The Brick Ironclad displaces more water than tactics strictly require. The Snap-Bricks are aware it is slow. They would like you to notice it is also still coming.',
    'navy-plush': 'The Pirate Plush Raft should not float, and knows it, and floats anyway — buoyed by cork, stubbornness, and a teddy figurehead who has claimed every puddle from here to the sink for the Horde.',
    'navy-racers': 'The RC Speedboat treats the bath as one long finish line photo. It has capsized four times, all of which it counts as podium finishes.',
    'navy-bots': 'The Tin Submarine runs silent, runs deep, and runs on a key it cannot reach by itself — which is why no submarine of the Bots ever sails alone. Listen at the drain some night. Tick. Tick.',
    galleon: 'The Toy Galleon is the bath\'s only capital ship, and it knows it — three sails of real cloth, a broadside of cork cannon, and a crow\'s nest from which, on a clear night, you can see the faucet at the edge of the world.',
    forgotten: 'The storybooks do not like this page. Toys boxed long enough learn to wind themselves, and what winds itself answers to no bedtime. They are not wicked. They are what waiting becomes when nobody says goodnight to it.',
    forgottenking: 'Before the tribes, before the room, a king was boxed with his crown still on. No scuffs. No name. No initials on his foot — because no one ever loved him carelessly enough to mark him. Everything he does, he does so that someone, anyone, will remember he was here.',
  },

  buildings: {
    chest: 'Every tribe\'s heart is a box with a lid. The Toy Chest is granary, barracks, capitol and bed all at once — and the last thing any toy sees before sleep, which is why they defend it like morning depends on it.',
    house: 'A Block House raises the ceiling of what a tribe dares to be: four more toys, then four more. The room\'s censuses are counted in rooftops.',
    mat: 'The Training Mat smells of rubber and resolve. Every soldier in the room did their first push-up here, and the mat remembers all of them by weight.',
    bench: 'The Craft Bench turns lollipop sticks and loose elastic into ranged superiority. Its sawdust is considered lucky.',
    garage: 'The Toy Garage never fully closes its door — something in there is always mid-tune, mid-repair, or mid-idea. Wheels enter tired and leave plotting.',
    workshop: 'The Siege Workshop is where the room\'s gentlest engineers build its least gentle machines. They hum while they work. The machines hum back.',
    farm: 'A Snack Mat is agriculture as the room understands it: crumbs arranged into rows, harvested on schedule, replanted by lunch. Empires march on it.',
    market: 'The Market runs on button-standard currency and gossip of equal value. Every price in the room is negotiable except the Delivery Cart\'s opinion of the routes.',
    basket: 'The Storage Basket is the empire\'s far-flung pocket — a place to set things down that quietly becomes a place worth defending.',
    tower: 'The Watchtower is a toy\'s height plus ambition. From up there the room stops being furniture and becomes a map, and maps win wars.',
    fort: 'The Fort is the argument made permanent: this floor is held. Kings are crowned in it, heroes muster from it, and no siege engine was ever built that didn\'t dream of it.',
    wall: 'Walls are the room\'s oldest sentence, written in blocks: "no." Everything a tribe loves lives behind one.',
    gate: 'A Gate is a wall that learned manners — it says "no" to enemies and "welcome home" to everyone else, and it has never once confused the two.',
    wonder: 'The Wonder is the only building in the room aimed at the future instead of the enemy. Finish it and the war simply concedes that your tribe was the one worth remembering.',
    dock: 'The Dock is where the floor ends and nerve begins. Harbor, shipyard and skimmer\'s rest — every navy the bath has ever feared started as one brave plank here.',
    tinker: 'The Tinker Bench never sleeps; it naps between breakthroughs. Half the room\'s upgrades were invented here, and the other half were invented here twice by accident.',
    tent: 'The Command Tent smells of canvas and cartography. Inside, General Greenboots plans by flashlight and insists — correctly — that no battle was ever lost in a properly squared tent.',
    brickshop: 'The Brick Foundry is the Snap-Bricks\' beating heart: molds in, marvels out. Its floor is the only place in the room where stepping on a brick is considered a blessing.',
    nest: 'The Pillow Nest is soft-power headquarters — nursery, hospital and barracks in one warm heap. Toys wounded anywhere in the room dream of being carried here.',
    pitstop: 'The Pit Stop measures its history in seconds saved. Fuel, fresh tires, and the Racers\' entire strategic reserve of bad ideas, all under one checkered awning.',
    robolab: 'The Robotics Bay hums at a frequency only gears love. It is the one building in the room that files its own maintenance reports, in triplicate, unprompted.',
  },

  maps: {
    playmat: 'The Bedroom Playmat is the room\'s old testament — every tribe\'s first war was fought across its printed roads. The milk spills are new. The grudges are not.',
    canyon: 'Toy Chest Canyon was born the day the big box tipped and the pillows fell like mountains. Three gaps thread the barricade, and every one of them is somebody\'s famous last stand.',
    underbed: 'Under the Bed is the room\'s frontier myth: dark, dusty, and older than anyone admits. Things live there that never came in a box. Scouts double their pay. Scouts earn it.',
    attic: 'The Attic War Table is where the room\'s history retires — and, once a year, un-retires. Rich ground, long sightlines, and dust that remembers every campaign fought across it.',
    playground: 'The Backyard Playground is the great outdoors as toys understand it: sun-bleached, sprinkler-threatened, and gloriously wide. The sandbox center has changed paws a hundred times.',
    kitchen: 'The Kitchen Table is the land of milk and bounty — richest ground in the room and the most treacherous, because nothing marches through milk and everything wants to.',
    bookshelf: 'Bookshelf Heights is the room\'s mountain country, terraced in literature. Hold the high shelves and you hold the weather; lose them and fight uphill through the poetry section.',
    livingroom: 'The Living Room is holiday country — tinsel horizons and present-shaped hills. Toys fight politely here, mostly, on account of the ornaments being witnesses.',
    bathtub: 'The Bathtub Armada was the room\'s first sea and remains its whole navy tradition: one warm basin, two determined docks, and a rubber duck the size of the moon.',
  },
};
